version: '3.2'
services:
  bbb-exporter:
    container_name: bbb-exporter
    image: greenstatic/bigbluebutton-exporter:v0.6.0
    network_mode: host
    volumes:
      # Can be removed if `RECORDINGS_METRICS_READ_FROM_DISK` is set to false (or omitted).
      # See https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations for details.
      - "/var/bigbluebutton:/var/bigbluebutton:ro"
    environment:
      BIND_IP: "127.0.0.1"
      RECORDINGS_METRICS_READ_FROM_DISK: "true"
    env_file:
      - bbb_exporter_secrets.env
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.20.0
    network_mode: host
    command:
      # Default commands from Dockerfile
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # Our custom commands - metrics will be stored for 400 days
      - "--storage.tsdb.retention.time=400d"
      - "--web.listen-address=127.0.0.1:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.1
    network_mode: host
    environment:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
      GF_SERVER_HTTP_PORT: "3001"
      GF_SERVER_ROOT_URL: "https://example.com/monitoring"
    volumes:
      - "grafana_data:/var/lib/grafana"
    restart: unless-stopped

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.0.1
    network_mode: host
    command:
      - "--path.rootfs=/host"
      - "--web.listen-address=127.0.0.1:9100"
    pid: "host"
    volumes:
      - type: "bind"
        source: "/"
        target: "/host"
        read_only: true
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
